### ISSUE TITLE
Library not working anymore, IOError

### ISSUE THREAD

**Issue by matze19999** [skhg/pyPremiumSIM#4]
I get this error while running the code:

`Traceback (most recent call last):
  File "C:\Users\mproell\AppData\Local\Temp\tempCodeRunnerFile.python", line 5, in <module>
    session.try_login("*****", "*****")
  File "C:\Users\mproell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pypremiumsim\PyPremiumSIM.py", line 68, in try_login
    return self.__handle_login_response(login_validation_response.content)
  File "C:\Users\mproell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pypremiumsim\PyPremiumSIM.py", line 48, in __handle_login_response
    raise IOError("Unknown error.")
OSError: Unknown error.`

**Comment by skhg** [comment]
Hi @matze19999 thanks for the bug report, I see some errors too, I think it's something to do with changed libraries in the default Python version in MacOS big sur. I'll try to fix it as time allows and post an update

**Comment by matze19999** [comment]
Thanks for your work!

I really appreciate it ☺️

**Comment by lmaertin** [comment]
This is related to #6. PR closes this (tested on latest MacOs)
